# Generated by Django 3.1.3 on 2020-11-16 13:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Salary')),
                ('position', models.CharField(max_length=100, verbose_name='Position name')),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Hall name')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labs.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Exhibit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Exhibit name')),
                ('author', models.CharField(max_length=100, verbose_name='Atuhor name')),
                ('material', models.CharField(max_length=100, verbose_name='Material name')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labs.hall')),
            ],
        ),
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Exc name')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Exc start')),
                ('term', models.PositiveSmallIntegerField(default=1, verbose_name='Term exc')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Exc price')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labs.employee')),
            ],
        ),
    ]
