# Generated by Django 3.1.3 on 2020-11-17 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_auto_20201117_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='labs.employee'),
        ),
    ]
